version: '3'

services:
  docker-app:
    container_name: docker-app-demo-dockerize
    image: docker-app-demo-dockerize
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8888:8080
    volumes:
      - /data/spring-boot-app