server:
  port: 8080
spring:
  profiles:
    active: '@spring.profiles.active@'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
debug: true
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_sample_dockerize?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password:
---
spring:
  profiles: docker
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring_boot_sample_dockerize;mode=mysql
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false